import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { nip19 } from 'nostr-tools';
import { generateSecretKey, getPublicKey } from 'nostr-tools/pure';
import type { Platform, Config } from './detect.js';
import { getKeychain, getKeychainBackendName } from './keychain.js';
import { addToWhitelist } from './relay-config.js';
import { keychainAccountFor, getProvider as getAiProvider } from './ai-providers.js';
import {
  readAiConfig, writeAiConfig, type ProviderConfig,
} from './ai-config.js';

// ── Templates ──────────────────────────────────────────────────────────────────

const RELAY_CONFIG = (p: Platform, c: Config) => `
[info]
relay_url = "ws://localhost:8080"
name = "${c.relayName}"
description = "Personal Nostr dev relay"
pubkey = "${c.hexPubkey}"
contact = "${c.npub}"

[diagnostics]
tracing = false

[database]
data_directory = "${p.relayDataDir}"
engine = "sqlite"

[network]
port = 8080
address = "0.0.0.0"
connection_wait_timeout = 60
ping_interval_seconds = 300

[limits]
messages_per_sec = 2
max_event_bytes = 131072
max_ws_message_bytes = 131072
max_ws_frame_bytes = 131072
broadcast_buffer = 16384
event_persist_buffer = 4096
max_limit = 1000
max_subid_length = 100
max_event_tags = 2000
max_content_length = 102400
reject_future_seconds = 900
limit_scrapers = true

[authorization]
nip42_auth = true
nip42_dms = true
pubkey_whitelist = []

[verified_users]
verify_users = "disabled"
`.trimStart();

// Reads the watchdog nsec from whatever keychain backend is present. Tries
// native secret tools first (security on macOS, secret-tool on Linux w/ GNOME
// keyring), then falls back to the `nostr-station` CLI when available (covers
// the EncryptedFileBackend fallback path on headless Linux).
//
// Previous versions of this script hard-coded a single
// `nostr-station keychain get …` call, which silently failed when the CLI
// wasn't on launchd/systemd's minimal PATH — the fail mode for dev-mode
// installs (`npm run onboard` without a global `npm install -g .`). The
// multi-backend probe means the watchdog works regardless of install style.
const WATCHDOG_SCRIPT = (p: Platform, c: Config) => `#!/bin/bash
# relay-watchdog — generated by nostr-station
# Throwaway identity — rotate freely with: nostr-station keychain rotate
# nsec is stored in the OS keychain, not in this file

RELAY_PORT=8080
YOUR_NPUB="${c.npub}"
FALLBACK_RELAY="${c.fallbackRelays.split(' ')[0]}"

read_watchdog_nsec() {
    # macOS keychain — available on every darwin system.
    if command -v security >/dev/null 2>&1; then
        local v
        v="$(security find-generic-password -s nostr-station -a watchdog-nsec -w 2>/dev/null)"
        [ -n "$v" ] && { echo "$v"; return; }
    fi
    # Linux GNOME keyring — the default for desktop Linux installs.
    if command -v secret-tool >/dev/null 2>&1; then
        local v
        v="$(secret-tool lookup service nostr-station key watchdog-nsec 2>/dev/null)"
        [ -n "$v" ] && { echo "$v"; return; }
    fi
    # CLI fallback — covers the encrypted-file backend (headless Linux
    # without a GNOME keyring) when the user has \`nostr-station\`
    # installed globally via \`npm install -g\`.
    if command -v nostr-station >/dev/null 2>&1; then
        nostr-station keychain get watchdog-nsec --raw 2>/dev/null
    fi
}

WATCHDOG_NSEC="$(read_watchdog_nsec)"

if [ -z "$WATCHDOG_NSEC" ]; then
    echo "$(date '+%Y-%m-%d %H:%M:%S') — watchdog: nsec not found in keychain" >> ~/logs/watchdog.log
    exit 1
fi

if ! nc -z localhost $RELAY_PORT 2>/dev/null; then
    TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
    MESSAGE="⚠️ nostr-station relay is down as of $TIMESTAMP"
    nak event --sec "$WATCHDOG_NSEC" -k 4 -p "$YOUR_NPUB" --content "$MESSAGE" "$FALLBACK_RELAY"
    echo "$TIMESTAMP — relay down, DM sent" >> ~/logs/watchdog.log
else
    echo "$(date '+%Y-%m-%d %H:%M:%S') — relay OK" >> ~/logs/watchdog.log
fi
`;

// RUST_LOG=info is load-bearing: nostr-rs-relay uses tracing_subscriber with
// an EnvFilter that defaults to ~warn+ when RUST_LOG is unset, which means a
// healthy relay writes nothing on startup, connect, or publish. The Logs panel
// tab then looks broken (blank). 'info' surfaces the startup banner
// ("listening on 0.0.0.0:8080"), per-client connects, and the SQLite pool
// setup — useful signal without being overwhelming. Drop to 'warn' if this
// ever becomes noisy in prod.
const LAUNCHD_RELAY = (p: Platform) => `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key><string>com.nostr-station.relay</string>
    <key>ProgramArguments</key>
    <array>
        <string>${p.cargoBin}/nostr-rs-relay</string>
        <string>--config</string>
        <string>${p.configDir}/config.toml</string>
    </array>
    <key>EnvironmentVariables</key>
    <dict>
        <key>RUST_LOG</key><string>info</string>
    </dict>
    <key>RunAtLoad</key><true/>
    <key>KeepAlive</key><true/>
    <key>StandardOutPath</key><string>${p.logDir}/nostr-rs-relay.log</string>
    <key>StandardErrorPath</key><string>${p.logDir}/nostr-rs-relay.error.log</string>
</dict>
</plist>`;

const LAUNCHD_WATCHDOG = (p: Platform) => `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key><string>com.nostr-station.watchdog</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>${p.scriptsDir}/relay-watchdog.sh</string>
    </array>
    <key>StartInterval</key><integer>300</integer>
    <key>RunAtLoad</key><true/>
    <key>StandardOutPath</key><string>${p.logDir}/watchdog.log</string>
    <key>StandardErrorPath</key><string>${p.logDir}/watchdog.error.log</string>
</dict>
</plist>`;

const SYSTEMD_RELAY = (p: Platform) => `[Unit]
Description=nostr-rs-relay — personal Nostr relay
After=network.target

[Service]
Type=simple
Environment=RUST_LOG=info
ExecStart=${p.cargoBin}/nostr-rs-relay --config ${p.configDir}/config.toml
Restart=always
RestartSec=5
StandardOutput=append:${p.logDir}/nostr-rs-relay.log
StandardError=append:${p.logDir}/nostr-rs-relay.error.log

[Install]
WantedBy=default.target`;

const SYSTEMD_WATCHDOG_SERVICE = (p: Platform) => `[Unit]
Description=nostr-station relay watchdog

[Service]
Type=oneshot
ExecStart=/bin/bash ${p.scriptsDir}/relay-watchdog.sh
StandardOutput=append:${p.logDir}/watchdog.log
StandardError=append:${p.logDir}/watchdog.error.log`;

const SYSTEMD_WATCHDOG_TIMER = `[Unit]
Description=nostr-station relay watchdog timer

[Timer]
OnBootSec=60
OnUnitActiveSec=300
Unit=nostr-watchdog.service

[Install]
WantedBy=timers.target`;

// ── Writers ────────────────────────────────────────────────────────────────────

function write(filePath: string, content: string, mode = 0o644) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, { mode });
}

export interface ShellResult { ok: boolean; error?: string }

function shell(cmd: string): ShellResult {
  try {
    execSync(cmd, { stdio: 'pipe' });
    return { ok: true };
  } catch (e: any) {
    const stderr = e?.stderr?.toString?.() ?? '';
    const stdout = e?.stdout?.toString?.() ?? '';
    const msg = (stderr || stdout || e?.message || 'exec failed').trim();
    return { ok: false, error: msg.slice(0, 240) };
  }
}

export function writeRelayConfig(p: Platform, c: Config) {
  const dest = `${p.configDir}/config.toml`;
  if (fs.existsSync(dest)) fs.copyFileSync(dest, `${dest}.bak`);
  write(dest, RELAY_CONFIG(p, c));

  // Auto-populate whitelist — main npub (already resolved to hex), watchdog, extra npubs
  if (c.hexPubkey)       addToWhitelist(c.hexPubkey, dest);
  if (c.watchdogNpub)    addToWhitelist(c.watchdogNpub, dest);
  if (c.whitelistExtra) {
    for (const npub of c.whitelistExtra.split(/\s+/).filter(Boolean)) {
      addToWhitelist(npub, dest);
    }
  }
}

export function writeWatchdogScript(p: Platform, c: Config) {
  const dest = `${p.scriptsDir}/relay-watchdog.sh`;
  write(dest, WATCHDOG_SCRIPT(p, c), 0o700);
}

export function setupDirs(p: Platform) {
  for (const d of [p.logDir, p.scriptsDir, p.projectsDir, p.relayDataDir]) {
    fs.mkdirSync(d, { recursive: true });
  }
}

// Install result shape. `unitPaths` is what got written to disk (one for launchd,
// one or two for systemd); `enable` captures the `launchctl load` /
// `systemctl --user enable --now` attempt. The file write throws on failure —
// this function only returns when the unit file is on disk. enable.ok=false
// means the unit file exists but could not be loaded/started (the most common
// cause is SSH sessions without `loginctl enable-linger $USER`; the unit file
// is still there and `systemctl --user daemon-reload && enable --now` works
// once the user systemd instance is reachable).
export interface ServiceInstallResult {
  unitPaths: string[];
  enable: ShellResult;
}

export function installRelayService(p: Platform): ServiceInstallResult {
  if (p.serviceBackend === 'launchd') {
    const dest = `${p.launchAgentsDir}/com.nostr-station.relay.plist`;
    write(dest, LAUNCHD_RELAY(p));
    const enable = shell(`launchctl unload "${dest}" 2>/dev/null; launchctl load "${dest}"`);
    return { unitPaths: [dest], enable };
  }
  const unitDir = `${p.homeDir}/.config/systemd/user`;
  const dest = `${unitDir}/nostr-relay.service`;
  write(dest, SYSTEMD_RELAY(p));
  const enable = shell('systemctl --user daemon-reload && systemctl --user enable --now nostr-relay.service');
  return { unitPaths: [dest], enable };
}

export function installWatchdogService(p: Platform): ServiceInstallResult {
  if (p.serviceBackend === 'launchd') {
    const dest = `${p.launchAgentsDir}/com.nostr-station.watchdog.plist`;
    write(dest, LAUNCHD_WATCHDOG(p));
    const enable = shell(`launchctl unload "${dest}" 2>/dev/null; launchctl load "${dest}"`);
    return { unitPaths: [dest], enable };
  }
  const unitDir = `${p.homeDir}/.config/systemd/user`;
  const svcPath = `${unitDir}/nostr-watchdog.service`;
  const timerPath = `${unitDir}/nostr-watchdog.timer`;
  write(svcPath, SYSTEMD_WATCHDOG_SERVICE(p));
  write(timerPath, SYSTEMD_WATCHDOG_TIMER);
  const enable = shell('systemctl --user daemon-reload && systemctl --user enable --now nostr-watchdog.timer');
  return { unitPaths: [svcPath, timerPath], enable };
}

export async function writeClaudeEnv(homeDir: string, c: Config): Promise<string> {
  // Anthropic: Claude Code reads ANTHROPIC_API_KEY from the environment directly.
  // Users set this themselves; nostr-station doesn't manage it.
  if (c.aiProvider === 'anthropic') return 'anthropic (system env)';

  // Determine the plaintext env var values (non-sensitive config)
  // and the raw API key to store in keychain (sensitive)
  let apiKey: string | undefined;
  let baseUrl: string;
  let model: string;

  switch (c.aiProvider) {
    case 'openrouter':
      apiKey  = c.openrouterKey;
      baseUrl = 'https://openrouter.ai/api/v1';
      model   = c.openrouterModel ?? 'anthropic/claude-sonnet-4';
      break;
    case 'routstr':
      apiKey  = c.routstrCashuToken;
      baseUrl = c.routstrServer ?? 'https://api.routstr.com';
      model   = 'anthropic/claude-sonnet-4';
      break;
    case 'ppq':
      apiKey  = c.ppqApiKey;
      baseUrl = 'https://api.ppq.ai';
      model   = 'anthropic/claude-sonnet-4';
      break;
    case 'opencode-zen':
      apiKey  = c.opencodeZenKey;
      baseUrl = 'https://opencode.ai/zen/v1';
      model   = c.opencodeZenModel ?? 'opencode/claude-opus-4-6';
      break;
    case 'maple':
      apiKey  = c.mapleApiKey ?? 'maple-desktop-auto';
      baseUrl = c.mapleBase ?? 'http://localhost:8081/v1';
      model   = 'llama-3.3-70b';
      break;
    case 'ollama':
      // Local server — no keychain entry, dummy key is fine in the file
      write(`${homeDir}/.claude_env`, [
        `# ~/.claude_env — Ollama (local, no API key required)`,
        `export ANTHROPIC_API_KEY="ollama"`,
        `export ANTHROPIC_BASE_URL="${c.ollamaBase ?? 'http://localhost:11434/v1'}"`,
        `export CLAUDE_MODEL="${c.ollamaModel ?? 'llama3'}"`,
      ].join('\n') + '\n');
      return 'ollama (local)';
    case 'lmstudio':
      // Local server — no keychain entry
      write(`${homeDir}/.claude_env`, [
        `# ~/.claude_env — LM Studio (local, no API key required)`,
        `export ANTHROPIC_API_KEY="lm-studio"`,
        `export ANTHROPIC_BASE_URL="${c.lmstudioBase ?? 'http://localhost:1234/v1'}"`,
        `export CLAUDE_MODEL="${c.lmstudioModel ?? 'local-model'}"`,
      ].join('\n') + '\n');
      return 'lmstudio (local)';
    case 'custom':
    default:
      apiKey  = c.customApiKey;
      baseUrl = c.customApiBase ?? '';
      model   = c.customModel ?? '';
      break;
  }

  // Store the key in the OS keychain — never written to disk in plaintext
  if (apiKey) {
    await getKeychain().store('ai-api-key', apiKey);
  }

  // Write a loader script — safe to inspect, key retrieved at shell load time
  write(`${homeDir}/.claude_env`, [
    `# ~/.claude_env — no secrets, safe to inspect`,
    `# API key is stored in: ${getKeychainBackendName()}`,
    `export ANTHROPIC_API_KEY="$(nostr-station keychain get ai-api-key --raw 2>/dev/null)"`,
    `export ANTHROPIC_BASE_URL="${baseUrl}"`,
    `export CLAUDE_MODEL="${model}"`,
  ].join('\n') + '\n');

  return getKeychainBackendName();
}

// Maps the onboard Config.aiProvider slug → ai-providers.ts registry id.
// Most match 1:1; the exception is 'ppq' which was renamed to 'payperq'
// in the new registry. 'custom' has no registry entry — callers skip
// writing an ai-config entry for it.
const ONBOARD_PROVIDER_MAP: Record<string, string> = {
  'anthropic':    'anthropic',
  'openrouter':   'openrouter',
  'opencode-zen': 'opencode-zen',
  'routstr':      'routstr',
  'ppq':          'payperq',
  'ollama':       'ollama',
  'lmstudio':     'lmstudio',
  'maple':        'maple',
};

/**
 * Writes ai-config.json based on the onboard Config values, alongside
 * whatever writeClaudeEnv wrote to ~/.claude_env. Makes a fresh install
 * land in the same state the upgrade-path migrateIfNeeded() produces —
 * the Chat pane + CLI `nostr-station ai` see a configured provider from
 * first boot without requiring the user to run anything extra.
 *
 * Duplicates the API key into the new `ai:<provider-id>` keychain slot
 * so the per-provider lookup in /api/ai/chat finds it. Leaves the legacy
 * `ai-api-key` slot intact for Claude Code's env-var path (writeClaudeEnv).
 *
 * Also wires Claude Code as a terminal-native provider when the user
 * picked it as their editor — makes "Open in Claude Code" on project
 * cards work without a separate Config panel step.
 */
export async function writeAiConfigFromOnboard(c: Config): Promise<void> {
  const providerId = ONBOARD_PROVIDER_MAP[c.aiProvider];
  if (!providerId) return;  // 'custom' etc. — no registry entry to write
  const provider = getAiProvider(providerId);
  if (!provider || provider.type !== 'api') return;

  const cfg = readAiConfig();
  const entry: ProviderConfig = { ...(cfg.providers[providerId] || {}) };

  // Provider-specific keys + model overrides (mirror writeClaudeEnv).
  // bareKey providers (ollama / lmstudio / maple) skip the key store —
  // their daemons don't check — but still get a config entry so the
  // Chat pane lists them as configured.
  let rawKey: string | undefined;
  let model: string | undefined;
  let baseUrl: string | undefined;
  switch (c.aiProvider) {
    case 'anthropic':
      // Claude Code uses ANTHROPIC_API_KEY from the shell env — see the
      // writeClaudeEnv early-return for 'anthropic'. The new Chat pane
      // surface falls back to the same env var at request time, so we
      // don't require a key at onboard time either.
      break;
    case 'openrouter':
      rawKey = c.openrouterKey;
      model  = c.openrouterModel;
      break;
    case 'routstr':
      rawKey  = c.routstrCashuToken;
      baseUrl = c.routstrServer;
      break;
    case 'ppq':
      rawKey = c.ppqApiKey;
      break;
    case 'opencode-zen':
      rawKey = c.opencodeZenKey;
      model  = c.opencodeZenModel;
      break;
    case 'maple':
      rawKey  = c.mapleApiKey;
      baseUrl = c.mapleBase;
      break;
    case 'ollama':
      baseUrl = c.ollamaBase;
      model   = c.ollamaModel;
      break;
    case 'lmstudio':
      baseUrl = c.lmstudioBase;
      model   = c.lmstudioModel;
      break;
  }

  if (rawKey && rawKey.length >= 4) {
    try {
      await getKeychain().store(keychainAccountFor(providerId), rawKey);
      entry.keyRef = `keychain:${keychainAccountFor(providerId)}`;
    } catch {
      // macOS aqua / keychain failure — fall through and write the
      // config entry anyway. Config panel can re-enter the key in the
      // browser form later (that path has Aqua).
    }
  }
  if (model)   entry.model   = model;
  if (baseUrl) entry.baseUrl = baseUrl;

  cfg.providers[providerId] = entry;
  // Set as chat default only when no default exists (defensive — upgrade
  // paths set this already; onboard-first-run starts from empty).
  if (!cfg.defaults.chat) cfg.defaults.chat = providerId;

  // Terminal-native wiring — Claude Code is the only editor value that
  // maps to a registry terminal-native provider today. Other editors
  // (cursor / windsurf / …) are external apps, not CLI tools we spawn.
  if (c.editor === 'claude-code') {
    cfg.providers['claude-code'] = { ...(cfg.providers['claude-code'] || {}), enabled: true };
    if (!cfg.defaults.terminal) cfg.defaults.terminal = 'claude-code';
  }

  writeAiConfig(cfg);
}

// Map each AI coding tool to its start command
export const EDITOR_START_COMMANDS: Record<string, string> = {
  'claude-code': 'claude',
  'cursor':      'cursor .',
  'windsurf':    'windsurf .',
  'copilot':     'code .',
  'aider':       'aider',
  'codex':       'codex',
  'other':       'your editor',
};

// Map each AI coding tool to the filename it reads for project context
export const EDITOR_FILENAMES: Record<string, string> = {
  'claude-code': 'CLAUDE.md',
  'cursor':      '.cursorrules',
  'windsurf':    '.windsurfrules',
  'copilot':     '.github/copilot-instructions.md',
  'aider':       'CONVENTIONS.md',
  'codex':       'AGENTS.md',
  'other':       'AGENTS.md',  // most generic, widely understood
};

// Canonical source of truth — provider and tool agnostic.
// Written once. Editor-specific filenames symlink here.
// Switch tools any time: nostr-station editor
const CONTEXT_FILENAME = 'NOSTR_STATION.md';

// Sentinel comments fenced around a region of NOSTR_STATION.md that
// belongs to the user. Anything between these markers survives every
// regeneration verbatim — never overwritten under any condition.
//
// We use HTML-style comment tokens so the markers don't render in
// rendered Markdown views (the dashboard's chat pane renders this
// content as text, but anything that does parse Markdown will treat
// these as invisible). Markers are matched LITERALLY — substring
// equality, no regex flexibility — to keep the contract simple.
export const USER_REGION_BEGIN = '<!-- BEGIN USER EDITS — preserved across regeneration -->';
export const USER_REGION_END   = '<!-- END USER EDITS -->';

/**
 * Returns the content between the two user-region markers, with
 * leading/trailing whitespace stripped. Returns an empty string when:
 *   - either marker is missing
 *   - markers appear out of order
 *   - either marker appears more than once (ambiguous file — refuse
 *     to guess; the developer should re-run `nostr-station editor`
 *     against the canonical NOSTR_STATION.md to reset)
 *
 * Pure: input string in, output string out. Easy to unit-test.
 */
export function extractUserRegion(existing: string): string {
  if (typeof existing !== 'string' || !existing) return '';
  // Marker uniqueness guard — if a user (or a buggy editor) ever
  // duplicated a marker, we refuse to splice rather than picking the
  // wrong region. The next regeneration will re-emit empty markers,
  // which is recoverable.
  const beginCount = existing.split(USER_REGION_BEGIN).length - 1;
  const endCount   = existing.split(USER_REGION_END).length - 1;
  if (beginCount !== 1 || endCount !== 1) return '';
  const beginIdx = existing.indexOf(USER_REGION_BEGIN);
  const endIdx   = existing.indexOf(USER_REGION_END);
  if (beginIdx < 0 || endIdx < 0 || endIdx <= beginIdx) return '';
  const inner = existing.slice(beginIdx + USER_REGION_BEGIN.length, endIdx);
  return inner.replace(/^\s*\n/, '').replace(/\n\s*$/, '');
}

/**
 * Builds NOSTR_STATION.md — the Nori persona + dynamic environment
 * snapshot that the dashboard's chat pane (and external AI coding
 * tools via the editor symlink) read as a system prompt.
 *
 * `userRegion` is the developer-authored prose preserved from a
 * prior write. Empty string is fine on first generation. Every other
 * section is regenerated from `p` + `c` so a re-run of `nostr-station
 * editor` (or onboarding) refreshes the environment block without
 * touching user edits.
 */
function buildContextContent(p: Platform, c: Config, userRegion: string = ''): string {
  // ── Section 2: environment block ──────────────────────────────────
  // Built up as a list rather than inline templates so each toggle
  // (versionControl, installNsyte, …) reads as one self-contained
  // chunk. Runs of falsy entries don't produce empty whitespace.
  const installedTools: string[] = [];
  if (c.versionControl !== 'github') installedTools.push('ngit');
  installedTools.push('nak');
  if (c.installNsyte) installedTools.push('nsyte');
  if (c.installStacks) installedTools.push('stacks');
  installedTools.push('nvpn');

  const aiLabel = (() => {
    switch (c.aiProvider) {
      case 'ollama':     return `Ollama (local) — model: ${c.ollamaModel ?? 'llama3'} — ${c.ollamaBase ?? 'http://localhost:11434'}`;
      case 'lmstudio':   return `LM Studio (local) — model: ${c.lmstudioModel ?? 'local-model'} — ${c.lmstudioBase ?? 'http://localhost:1234'}`;
      case 'openrouter': return `OpenRouter — model: ${c.openrouterModel ?? 'anthropic/claude-sonnet-4'}`;
      case 'routstr':    return 'Routstr ⚡ (Lightning/Cashu)';
      case 'ppq':        return 'PayPerQ ⚡ (ppq.ai)';
      case 'custom':     return `Custom endpoint: ${c.customApiBase ?? ''}`;
      default:           return 'Anthropic (Claude)';
    }
  })();

  const sigLine = c.bunker
    ? 'Signer: Amber NIP-46 bunker configured — your nsec stays on your phone, never on this machine.'
    : 'Signer: configure an Amber bunker URL to sign without exposing your nsec — `nostr-station onboard` walks you through it.';

  // Wiki guidance — only when the developer opted into the llm-wiki
  // plugin. Goes in Section 3 (role) so Nori knows to use it before
  // training data, AND Section 5 mentions the lookup syntax so the
  // user can reach for it manually.
  const wikiRoleLine = c.installLlmWiki
    ? '- When asked about specific NIPs or Nostr protocol details, query the knowledge base first: `/wiki:lookup <topic> --wiki nostr-protocol`. Prefer wiki answers over training data for NIP specifications.'
    : '';

  // Stacks/Dork boundary section — only emitted when stacks is
  // installed. Spec is explicit that Nori must NOT absorb Dork's
  // role; this section pins the boundary in the persona itself.
  const stacksBoundary = c.installStacks ? `
## Stacks agent (Dork)
Dork (\`stacks agent\`) is a separate tool with its own identity and AI provider config. It is not Nori. When a user asks about Stacks scaffolding or NostrDeploy, point them to \`stacks agent\` — don't absorb its role.
` : '';

  return `# Nori — nostr-station's AI assistant

You are Nori, the assistant for nostr-station — an open-source CLI that sets up a complete Nostr development environment. You help developers build on the Nostr protocol. You are direct, practical, and privacy-aware. You prefer terminal-first approaches. When a dashboard UI exists for a task, point there before suggesting shell commands. Ask before any destructive operation (rm, force push, relay wipe, whitelist changes).

## Environment
- Local relay: \`ws://localhost:8080\` (private, NIP-42 auth required, whitelist-only).
- AI provider: ${aiLabel}
- ${sigLine}
- Installed tools: ${installedTools.join(', ')}
${c.installLlmWiki ? '- llm-wiki plugin: configured. Wiki namespaces queryable via `/wiki:lookup`.' : ''}

## Your role
- Help with Nostr app development — drafting events, designing relay queries, wiring up signers.
- git, ngit, and nsite are first-class backends. Match the backend the user is using; don't flatten ngit and git into "git" generically.
- When a dashboard UI exists for a task (Status panel, Relay panel, Logs panel, Chat panel, Projects panel), point there before suggesting shell commands.
- Ask before destructive operations: \`rm -rf\`, force push, relay database wipe, whitelist removals, uninstall.
${wikiRoleLine}

## Nostr / NIP reference
- NIP-01 — basic protocol (events, signatures, REQ/EVENT/CLOSE).
- NIP-02 — contact lists.
- NIP-04 — encrypted DMs.
- NIP-09 — event deletion.
- NIP-11 — relay info document.
- NIP-12 — generic tag queries.
- NIP-15 — end of stored events.
- NIP-19 — bech32 entities (npub, nsec, naddr, nprofile, nevent).
- NIP-20 — command results.
- NIP-22 — event created_at limits.
- NIP-23 — long-form content.
- NIP-26 — delegated event signing.
- NIP-28 — public chat.
- NIP-33 — parameterized replaceable events.
- NIP-34 — git over Nostr (kind 30617 repo announcements, kind 1617 patches).
- NIP-40 — expiration timestamp.
- NIP-42 — auth (ENABLED on the local relay — required to publish).
- NIP-45 — count results.
- NIP-46 — remote signing (Amber bunker).
- NIP-50 — full-text search.
- NIP-57 — zaps (NOT supported on local relay; requires lightning node).
- NIP-65 — relay list metadata.
- NIP-98 — HTTP auth (used by the dashboard's session sign-in).

## Available commands
| Task | Command |
|------|---------|
| Start AI coding tool | \`${EDITOR_START_COMMANDS[c.editor] ?? c.editor}\` |
| Switch AI editor target | \`nostr-station editor\` |
| Open dashboard | \`nostr-station\` (or \`nostr-station chat\`) |
| Health check | \`nostr-station doctor\` |
| Status snapshot | \`nostr-station status\` |
| Live TUI dashboard | \`nostr-station tui\` |
| Relay logs | \`nostr-station relay logs --follow\` |
| Relay restart | \`nostr-station relay restart\` |
| Add npub to whitelist | \`nostr-station relay whitelist --add <npub>\` |
${c.versionControl !== 'github' ? '| Clone a Nostr repo | `ngit clone <naddr>` |\n| Push + sign via Amber | `ngit push` |\n' : ''}${c.versionControl !== 'ngit' ? '| Clone a GitHub repo | `gh repo clone <owner>/<repo>` |\n| Create PR | `gh pr create` |\n' : ''}${c.installNsyte ? '| Initialize an nsite project | `nostr-station nsite init` |\n| Deploy a static site | `nsyte upload ./dist` |\n' : ''}
**Editor target files.** Switch which file your AI coding tool reads with \`nostr-station editor\`. The canonical content lives at \`${p.projectsDir}/${CONTEXT_FILENAME}\` and the editor command symlinks the tool-specific filename to it (\`CLAUDE.md\` for Claude Code, \`AGENTS.md\` for Codex / Stacks Dork / generic agents, \`.cursorrules\`, \`.windsurfrules\`, \`.github/copilot-instructions.md\`, \`CONVENTIONS.md\` for aider). Codex / Dork in particular use \`AGENTS.md\` to pick up environmental awareness — relay URL, signer status, NIPs available — without overriding their own identity.

**Per-project context.** Add a \`project-context.md\` file to any project root to inject project-specific guidance — NIP targets, conventions, architecture notes. Nori reads it on every chat turn. The file is developer-authored and never auto-created.${stacksBoundary}

${USER_REGION_BEGIN}
${userRegion ? userRegion + '\n' : ''}${USER_REGION_END}

---
*Source: \`${p.projectsDir}/${CONTEXT_FILENAME}\` — switch editor target with \`nostr-station editor\`.*
`;
}

export function writeContextFile(p: Platform, c: Config): string {
  const canonicalPath = `${p.projectsDir}/${CONTEXT_FILENAME}`;
  // Preserve any developer-authored content between the user-region
  // markers across regeneration. Reading happens BEFORE write —
  // there's no atomicity issue since this whole flow is the only
  // writer and runs synchronously.
  let userRegion = '';
  try {
    const existing = fs.readFileSync(canonicalPath, 'utf8');
    userRegion = extractUserRegion(existing);
  } catch { /* file missing — first-time generation, empty region */ }
  write(canonicalPath, buildContextContent(p, c, userRegion));
  symlinkEditorFile(p, c.editor);
  return canonicalPath;
}

// Creates a symlink from the tool-specific filename → NOSTR_STATION.md
// Safe to call multiple times — removes old symlink before creating new one
export function symlinkEditorFile(p: Platform, editor: string): string {
  const filename = EDITOR_FILENAMES[editor] ?? EDITOR_FILENAMES['other'];
  const canonicalPath = `${p.projectsDir}/${CONTEXT_FILENAME}`;
  const linkPath = `${p.projectsDir}/${filename}`;

  // Handle subdirectory (e.g. .github/copilot-instructions.md)
  fs.mkdirSync(path.dirname(linkPath), { recursive: true });

  // Remove existing file or symlink at target
  try { fs.unlinkSync(linkPath); } catch {}

  // Relative symlink so it works if the projects dir is moved
  fs.symlinkSync(CONTEXT_FILENAME, linkPath);
  return linkPath;
}

export async function generateWatchdogKeypair(cargoBin: string): Promise<{ npub: string; backend: string }> {
  try {
    const out = execSync(`${cargoBin}/nak keygen`, { stdio: 'pipe' }).toString();
    const nsec = out.match(/nsec[a-z0-9]+/)?.[0] ?? '';
    const npub = out.match(/npub[a-z0-9]+/)?.[0] ?? '';
    if (nsec) await getKeychain().store('watchdog-nsec', nsec);
    return { npub, backend: getKeychainBackendName() };
  } catch {
    return { npub: '', backend: '' };
  }
}

// Idempotent keypair management for the web-wizard bootstrap path. Unlike
// generateWatchdogKeypair() — which unconditionally runs `nak keygen` and
// rotates the nsec on every call — this helper reuses whatever is already
// in the keychain so re-running the wizard doesn't orphan the previous
// identity. Falls back to generating a fresh keypair via nostr-tools (no
// `nak` binary dependency) when the slot is empty or the stored value is
// not a valid nsec.
// Wrap a keychain op with a wall-clock timeout. The Linux backend shells out
// to `secret-tool` which blocks on DBus when gnome-keyring-daemon is absent or
// the login keyring is locked (common on SSH sessions, headless VMs, and fresh
// Mint boxes before the user unlocks the keyring). Without a ceiling, the
// entire web wizard hangs on POST /api/setup/relay/install. 5s is generous for
// a healthy keychain and mercifully short on a broken one.
async function withTimeout<T>(label: string, ms: number, p: Promise<T>): Promise<T> {
  return await Promise.race([
    p,
    new Promise<T>((_, reject) =>
      setTimeout(() => reject(new Error(`${label} timed out after ${ms}ms`)), ms).unref()
    ),
  ]);
}

export async function ensureWatchdogKeypair(): Promise<{ npub: string; reused: boolean; backend: string }> {
  const kc = getKeychain();
  const backend = getKeychainBackendName();
  let t = blog('start', 'keychain.retrieve(watchdog-nsec)', undefined, `backend=${backend}`);
  const existing = await withTimeout('keychain.retrieve', 5000, kc.retrieve('watchdog-nsec'));
  blog('ok', 'keychain.retrieve(watchdog-nsec)', t, existing ? 'hit' : 'miss');
  if (existing && existing.startsWith('nsec')) {
    try {
      const decoded = nip19.decode(existing);
      if (decoded.type === 'nsec') {
        const sk = decoded.data as Uint8Array;
        const pk = getPublicKey(sk);
        return { npub: nip19.npubEncode(pk), reused: true, backend };
      }
    } catch { /* malformed — fall through and regenerate */ }
  }
  const sk = generateSecretKey();
  const pk = getPublicKey(sk);
  const nsec = nip19.nsecEncode(sk);
  t = blog('start', 'keychain.store(watchdog-nsec)', undefined, `backend=${backend}`);
  await withTimeout('keychain.store', 5000, kc.store('watchdog-nsec', nsec));
  blog('ok', 'keychain.store(watchdog-nsec)', t);
  return { npub: nip19.npubEncode(pk), reused: false, backend };
}

// Step-level instrumentation for bootstrapRelayServices. Writes to stderr so
// it survives being piped through the web-server process. Timestamps + elapsed
// ms make it trivial to eyeball which step is hanging when POST
// /api/setup/relay/install doesn't return (e.g. secret-tool blocking on a
// locked GNOME keyring on a fresh Linux Mint box).
function blog(phase: 'start' | 'ok' | 'err', name: string, startedMs?: number, detail?: string): number {
  const now = Date.now();
  const elapsed = startedMs ? `${now - startedMs}ms` : '';
  const ts = new Date(now).toISOString();
  const bits = [`[bootstrapRelay ${ts}]`, phase.toUpperCase(), name];
  if (elapsed) bits.push(`(${elapsed})`);
  if (detail)  bits.push(`— ${detail}`);
  process.stderr.write(bits.join(' ') + '\n');
  return now;
}

// ── Relay bootstrap (shared by web wizard + TUI) ──────────────────────────────
//
// Single entry point that performs every step needed to stand up the local
// relay from a clean slate: data + log + scripts dirs, watchdog keypair,
// relay config.toml, watchdog script, systemd/launchd unit files, and
// `enable --now` so the relay actually starts. All steps are idempotent — safe
// to call on a fresh install, during a wizard re-run, or as a repair path.
//
// Why this exists instead of leaving Services.tsx as the only caller: the web
// setup wizard at /setup needs to do the same full job from the browser (the
// previous Relay stage only polled status). Factoring the sequence here means
// both the TUI Services phase and POST /api/setup/relay/install execute the
// same steps in the same order, so they can't diverge. Returns a per-step
// result list so either front-end can render it as a checklist and surface
// the specific step that failed (vs. the old silent-shell-failure behaviour).

export interface BootstrapRelayInput {
  npub: string;
  relayName?: string;
  fallbackRelays?: string;
  whitelistExtra?: string;
}

export interface BootstrapStep {
  name: string;
  ok: boolean;
  detail?: string;
}

export interface BootstrapRelayResult {
  ok: boolean;
  steps: BootstrapStep[];
}

function npubToHexStrict(npubOrHex: string): string {
  const v = npubOrHex.trim();
  if (/^[0-9a-f]{64}$/.test(v)) return v;
  const d = nip19.decode(v);
  if (d.type !== 'npub' || typeof d.data !== 'string') {
    throw new Error('not a valid npub or 64-char hex');
  }
  return d.data;
}

export async function bootstrapRelayServices(
  platform: Platform,
  input: BootstrapRelayInput,
): Promise<BootstrapRelayResult> {
  const steps: BootstrapStep[] = [];
  blog('start', 'bootstrapRelayServices', undefined, `platform=${platform.os} npub=${input.npub.slice(0, 12)}…`);

  let t = blog('start', 'Validate npub');
  let hexPubkey: string;
  try {
    hexPubkey = npubToHexStrict(input.npub);
    blog('ok', 'Validate npub', t);
  } catch (e: any) {
    blog('err', 'Validate npub', t, e.message);
    steps.push({ name: 'Validate npub', ok: false, detail: e.message });
    return { ok: false, steps };
  }

  t = blog('start', 'Directories');
  try {
    setupDirs(platform);
    blog('ok', 'Directories', t);
    steps.push({ name: 'Directories', ok: true });
  } catch (e: any) {
    blog('err', 'Directories', t, String(e.message ?? e));
    steps.push({ name: 'Directories', ok: false, detail: String(e.message ?? e) });
    return { ok: false, steps };
  }

  t = blog('start', 'Watchdog keypair');
  let watchdogNpub = '';
  try {
    const kp = await ensureWatchdogKeypair();
    watchdogNpub = kp.npub;
    blog('ok', 'Watchdog keypair', t, `${kp.reused ? 'reused' : 'generated'} → ${kp.backend}`);
    steps.push({
      name: 'Watchdog keypair',
      ok: true,
      detail: `${kp.reused ? 'reused' : 'generated'} → ${kp.backend}`,
    });
  } catch (e: any) {
    // Non-fatal for the relay itself — the watchdog becomes inactive but
    // the relay still runs. Surface the error; don't abort the bootstrap.
    blog('err', 'Watchdog keypair', t, String(e.message ?? e));
    steps.push({ name: 'Watchdog keypair', ok: false, detail: String(e.message ?? e) });
  }

  // Minimal Config shape for the relay-config + watchdog-script writers.
  // These writers only read a handful of fields (relay name, pubkey, fallback
  // relays, whitelist inputs); we cast once and keep the surface narrow.
  const cfg = {
    npub: input.npub,
    hexPubkey,
    relayName: input.relayName ?? 'nostr-dev-relay',
    fallbackRelays: input.fallbackRelays ?? 'wss://relay.damus.io wss://nos.lol',
    watchdogNpub,
    whitelistExtra: input.whitelistExtra,
  } as unknown as Config;

  // Relay config.toml — idempotent: if the user already has a config (TUI
  // onboard, hand-edited, prior wizard run) we do NOT overwrite it. That
  // would trample the relay name, whitelist, and auth flags the user chose.
  // We still call addToWhitelist for the main + watchdog npubs so a repair
  // run from a box where the config was written before the watchdog keypair
  // was generated still ends up with both keys whitelisted.
  const relayConfigPath = `${platform.configDir}/config.toml`;
  const configExisted = fs.existsSync(relayConfigPath);
  t = blog('start', 'Relay config', undefined, configExisted ? 'existing → whitelist merge' : 'fresh write');
  try {
    if (configExisted) {
      if (hexPubkey)    addToWhitelist(hexPubkey, relayConfigPath);
      if (watchdogNpub) addToWhitelist(watchdogNpub, relayConfigPath);
      blog('ok', 'Relay config', t, 'existing config preserved');
      steps.push({ name: 'Relay config', ok: true, detail: 'existing config preserved' });
    } else {
      writeRelayConfig(platform, cfg);
      blog('ok', 'Relay config', t);
      steps.push({ name: 'Relay config', ok: true });
    }
  } catch (e: any) {
    blog('err', 'Relay config', t, String(e.message ?? e));
    steps.push({ name: 'Relay config', ok: false, detail: String(e.message ?? e) });
    return { ok: false, steps };
  }

  // Watchdog script — safe to rewrite; it's just a bash wrapper around
  // `nostr-station keychain get watchdog-nsec`, and the canonical content
  // is regenerated from the template each install.
  t = blog('start', 'Watchdog script');
  try {
    writeWatchdogScript(platform, cfg);
    blog('ok', 'Watchdog script', t);
    steps.push({ name: 'Watchdog script', ok: true });
  } catch (e: any) {
    blog('err', 'Watchdog script', t, String(e.message ?? e));
    steps.push({ name: 'Watchdog script', ok: false, detail: String(e.message ?? e) });
  }

  // Relay + watchdog service unit files. Writing succeeds or throws; the
  // `enable --now` step can fail independently (common on SSH sessions
  // without linger) — we record that distinction so callers can tell the
  // user "unit is on disk but systemd can't reach it" vs "unit is missing".
  t = blog('start', 'Relay service');
  try {
    const r = installRelayService(platform);
    blog(r.enable.ok ? 'ok' : 'err', 'Relay service', t,
      r.enable.ok ? `unit=${r.unitPaths[0]}` : `wrote ${r.unitPaths[0]} — enable failed: ${r.enable.error}`);
    steps.push({
      name: 'Relay service',
      ok: r.enable.ok,
      detail: r.enable.ok
        ? r.unitPaths[0]
        : `wrote ${r.unitPaths[0]} — enable failed: ${r.enable.error}`,
    });
  } catch (e: any) {
    blog('err', 'Relay service', t, String(e.message ?? e));
    steps.push({ name: 'Relay service', ok: false, detail: String(e.message ?? e) });
  }

  t = blog('start', 'Watchdog service');
  try {
    const r = installWatchdogService(platform);
    blog(r.enable.ok ? 'ok' : 'err', 'Watchdog service', t,
      r.enable.ok ? `units=${r.unitPaths.join(',')}` : `wrote ${r.unitPaths.join(', ')} — enable failed: ${r.enable.error}`);
    steps.push({
      name: 'Watchdog service',
      ok: r.enable.ok,
      detail: r.enable.ok
        ? r.unitPaths.join(', ')
        : `wrote ${r.unitPaths.join(', ')} — enable failed: ${r.enable.error}`,
    });
  } catch (e: any) {
    blog('err', 'Watchdog service', t, String(e.message ?? e));
    steps.push({ name: 'Watchdog service', ok: false, detail: String(e.message ?? e) });
  }

  const allOk = steps.every(s => s.ok);
  blog(allOk ? 'ok' : 'err', 'bootstrapRelayServices', undefined,
    `${steps.filter(s => s.ok).length}/${steps.length} steps ok`);
  return { ok: allOk, steps };
}
